### ISSUE TITLE
Add package updates to Releases in Github

### ISSUE THREAD

**Issue by evanheckert** [jonathan-s/djantic2#1]
Thanks for this fork! I was bummed to see Djantic abandoned(ish), then thrilled to see your issue posted there about this fork.

I always "watch" the releases on a repo for a package I use - would you mind using that feature when you push a new version so we're prompted to come see what's new?

Thanks again!

**Comment by jonathan-s** [comment]
Sure, I will do that for future releases, though since this package seems pretty stable and there aren't any feature wishlist or bugs per se now. I don't really know when a next version would be released.
