### ISSUE TITLE
Query: v1.0.5 not published to PyPi

### ISSUE THREAD

**Issue by htsaustin** [jonathan-s/djantic2#19]
Will the Pydantic 2.10 fix, in v1.0.5, be published to PyPi soon? 

Thanks for all the work on Djantic2!

**Comment by jonathan-s** [comment]
I just noticed! Looks like I need to double-check that automation.

**Comment by jonathan-s** [comment]
@htsaustin I'll have to be more mindful the next time I make a release, it looks like the automation was not triggered for whatever reason. It's on pypi now.
