### ISSUE TITLE
Related fields are not nullable

### ISSUE THREAD

**Issue by marcy-buccellato** [jonathan-s/djantic2#5]
If a field is marked `null=True`, the annotation is marked `Union[type, None]` (https://github.com/jonathan-s/djantic2/blob/main/djantic/fields.py#L169). This is the expected behavior, but that does not seem to happening for related fields. I believe we need to add that same logic here: https://github.com/jonathan-s/djantic2/blob/main/djantic/fields.py#L114.

**Comment by marcy-buccellato** [comment]
@jonathan-s Can you please take a look at this? I can open a PR if you think this makes sense.

**Comment by marcy-buccellato** [comment]
https://github.com/jonathan-s/djantic2/pull/7

**Comment by jonathan-s** [comment]
@marcy-buccellato Now the latest version is on pypi.
